### ISSUE TITLE
[BUG] Update README to reflect the correct class for JWE configuration object

### ISSUE THREAD

**Issue by SpaceBaar** [Mastercard/client-encryption-java#17]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
We are trying to use the new JWE Encryption with our Send 2.0 Implementation.
The README for this library states to pass an EncryptionConfig instance, but the JweEncryption.encryptPayload method actually requires us to pass an JweConfig instance.

**To Reproduce**
1. Add client-encryption dependency in your project.
2. Create JWE Encryption configuration as mentioned in the [README](https://github.com/Mastercard/client-encryption-java#configuring-the-jwe-encryption-)
3. Pass this Encryption config instance to the JweEncryption.encryptPayload method with the request payload.
4. IDE throws the error "The method encryptPayload(String, JweConfig) in the type JweEncryption is not applicable for the arguments (String, EncryptionConfig)"

**Expected behavior**
The documentation should be updated to reflect the correct class for JWE configuration object.

**Screenshots**
README documentation states to use instance of EncryptionConfig:
<img width="1020" alt="Screenshot 2021-06-07 at 12 59 36 PM" src="https://user-images.githubusercontent.com/21951897/120977170-a9a03900-c790-11eb-962f-360449262032.png">

JweEncryption.encryptPayload method requires instance of JweConfig:
<img width="1018" alt="Screenshot 2021-06-07 at 1 00 02 PM" src="https://user-images.githubusercontent.com/21951897/120977198-b0c74700-c790-11eb-98d2-05a66f612122.png">

**Comment by jaaufauvre** [comment]
Fixed by #18
