### ISSUE TITLE
[BUG] Can't set JSON engine in JsonParser

### ISSUE THREAD

**Issue by simmons-square** [Mastercard/client-encryption-java#40]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
The README says we should be able to set a specific JsonEngine in the JsonParser class. However, in the latest released version 1.7.1, the JsonParser class is package-private and the method `withJsonEngine` is also package-private.

**To Reproduce**
Add the documented call
```
JsonParser.withJsonEngine(new JettisonJsonEngine());
```
to any `static` block in a class. The call does not resolve.

**Expected behavior**
Should be able to change the JsonEngine. We'd like this feature because we want to ensure the same JsonEngine is selected regardless of other dependencies we may include on our classpath.

**Screenshots**
N/A

**Additional context**

**Related issues/PRs**
Has a similar issue/PR been reported/opened before?

**Suggest a fix/enhancement**
Make `JsonParser` public and the `withJsonEngine` method public

**Comment by Akshaykdubey** [comment]
Hi @simmons-square, thanks for raising the Bug. 
We acknowledge this, will review and come back with an update shortly.
Thanks!

**Comment by jaaufauvre** [comment]
Fixed in https://github.com/Mastercard/client-encryption-java/releases/tag/v1.7.2
