### ISSUE TITLE
[REQ] add maven wrapper functionality

### ISSUE THREAD

**Issue by nikitakoselev** [Mastercard/client-encryption-java#49]
### Is your feature request related to a problem? Please describe.

I am always frustrated when I need to select a specific version of maven/gradle for the project.
Even if the project builds, I still want to use the very same version as the one it was created with.

### Describe the solution you'd like
Utilize "maven wrapper" functionality, similar to the "Gradle wrapper" one.

### Describe alternatives you've considered
We could move to gradle and use gradle's wrapper, but I prefer incremental and simple solutions.

### Additional context
https://maven.apache.org/wrapper/

**Comment by rfeelin** [comment]
Thanks for your PR but we've decided to reject your contribution. We don't think this is a big enough issue to warrant this fix.
