### ISSUE TITLE
[REQ] Support json path wildcards

### ISSUE THREAD

**Issue by connerza** [Mastercard/client-encryption-java#52]
### Is your feature request related to a problem? Please describe.

Imagine a scenario in which there are multiple values that need to be encrypted/decrypted within a json list. The list can have an arbitrary number of items. It is impossible to specify an encryption path that matches each of these items. When I try this, I get `java.lang.IllegalArgumentException: JSON paths for encryption must point to a single item!`

```
{
  "items": [
    {
      "value": "foo1",
      ...
    },
    {
      "value": "foo2",
      ...
    },
    ...
  ] 
}
```

### Describe the solution you'd like

We should be able to specify an encryptionPath with a wildcard such as `$.items[*].value`

### Describe alternatives you've considered

Workaround we will use is to encrypt the entire list, although we'd prefer to only encrypt the necessary attribute.

### Additional context
n/a

**Comment by rfeelin** [comment]
Hi @connerza 

Thanks for your request. At this time we have no plans to implement wildcard JSON paths.
Ideally, we prefer if services encrypt entire payloads. Allowing individual fields is still left for edge cases like auditing, huge payloads etc. This is to keep things as simple as possible. 

For your example rather than end up with something like 
```
{
  "items": [
    {
      "encryptedData1": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...
    },
    {
      "encryptedData2": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...
    },
  ] 
}
```
would it not be better to places the encryption on the items field so it results in something like
```
{
  "encryptedData": "asdfasdbfvkajbdv.asdfkjbasvkjbkrljbv...
}
```
So the end-user only has to decrypt one field rather than run it against each field in the list?

**Comment by connerza** [comment]
Hi @rfeelin, thanks for your response! For our use case, we want to only encrypt certain attributes within the list while leaving other attributes in plain text for auditing and debugging purposes. So rather than looking like

```
{
  "items": [
    {
      "encryptedData1": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...
    },
    {
      "encryptedData2": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...
    },
  ] 
}
```
it looks something more like
```
{
  "items": [
    {
        "sensitiveData": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...,
        "nonSensitiveData1": "hello",
        "nonSensitiveData2": "world",
        ...
    },
    {
        "sensitiveData": "ngaarekjgnrelkjgna.rbakjrbgkjerbg...,
        "nonSensitiveData1": "hello",
        "nonSensitiveData2": "world",
        ...
    },
  ] 
}
```

**Comment by rfeelin** [comment]
Ah getcha! I'll bring this up with the team and schedule it for a future iteration.

**Comment by rfeelin** [comment]
@connerza the latest version of the plugin now has support for wildcards. Can you validate that this is working as expected?
