### ISSUE TITLE
[REQ] InputStream param for loadDecryptionKey(), loadEncryptionCertificate()

### ISSUE THREAD

**Issue by viliokas** [Mastercard/client-encryption-java#56]
### Is your feature request related to a problem?

 In method **EncryptionUtils.loadDecryptionKey(decryptionKeyPath)**
**decryptionKeyPath** path is required, this do not work when project is packaged in JAR.
I package Spring boot project with maven in to JAR and run in on docker.

### Describe the solution you'd like

Maybe you can add additional method with InputStream param:
**EncryptionUtils.loadDecryptionKey(InputStream decryptionKeyInputStream)**
As you have it in **AuthenticationUtils.loadSigningKey(InputStream pkcs12KeyInputStream)**
also please do the same with **EncryptionUtils.loadEncryptionCertificate(certificatePath).**

### Describe alternatives you've considered

Currently I did work around overriding your existing methods impl.

**Comment by danny-gallagher** [comment]
@viliokas Thanks for creating the issue!

You mentioned that you've created a workaround overriding our existing method for loading the key.
We would be happy to have a look at your implementation if you'd like to create a PR.
