### ISSUE TITLE
[REQ] Feature Request Being able to incorporate visa api

### ISSUE THREAD

**Issue by tomihc123** [Mastercard/client-encryption-java#67]
I would like this library to also work for visa.

**Comment by TutteRamson** [comment]
As stated in the [ReadMe file](https://github.com/Mastercard/client-encryption-java#introduction-), 
_this library supports two types of encryption/decryption, both of which support field level and entire payload encryption: JWE encryption and what the library refers to as Field Level Encryption (Mastercard encryption), a scheme used by many services hosted on Mastercard Developers before the library added support for JWE._

JWE Encryption follows the industry standard and you may use it to deal with Non-Mastercard services. As it is open source you may tweak it to meet your needs.

As owners of this library, we will ensure the version we offer works for [Mastercard Developers](https://developer.mastercard.com/apis) hosted services. Thanks for your interest.
