### ISSUE TITLE
Example of certificate fingerprint is unclear

### ISSUE THREAD

**Issue by ypwu1** [Mastercard/client-encryption-java#7]
We have done client implementation encryption for instance provisioning, not in java but in go. we use all test sample and test case to verify our implementation. Everything went well until we hit api. Failed on first step:  Fingerprint verification. The fact is the fingerprint is for public certificate, not for key.  The term "Pulbickey fingerprint" is confused. Mastercard api require fingerprint is for certificate, not for the public key generated from certificate. It would be good on documentation comments it out or example for that.

**Comment by prithuadhikary** [comment]
Hello Oscar,

Please mention which api you are consuming. But FYI, the public key
fingerprint sent in the payload is used to identify the private key to be
used for decrypting the payload at the sever side. Furthermore, as far as I
know we do not even store or receive the certificate being used by the
client for encrypting the payload at server side, so it is not possible to
identify the private key based on certificate fingerprint.
So IMHO, setting the public key fingerprint in the payload should resolve
your issue. If you scan through the code you would see it being computed as
the SHA2 digest of the public key, encoded as ASN.1 octet sequence.

Hope this helps.

Thanks and Regards,
Prithu

**Comment by jaaufauvre** [comment]
>The term "Pulbickey fingerprint" is confused.
>It would be good on documentation comments it out or example for that.

This project uses "_encryption key fingerprint_" or "_encryption certificate fingerprint_" to designate what value to use as key identifier. 

There should be no confusion here. Can you please provide a link to the documentation you are talking about?

See also:
* [Service Configurations in Java](https://github.com/Mastercard/client-encryption-java/wiki/Service-Configurations-in-Java)
* [FieldLevelEncryptionConfigBuilder.java#L216](https://github.com/Mastercard/client-encryption-java/blob/master/src/main/java/com/mastercard/developer/encryption/FieldLevelEncryptionConfigBuilder.java#L216)

**Comment by ypwu1** [comment]
@jaaufauvre we were working on [push-provisioning](https://developer.mastercard.com/page/push-provisioning) which uses mastercard api indirectly.  And I used another [mastercard-api-client-tutorial](https://github.com/Mastercard/mastercard-api-client-tutorial) as reference.

**Comment by ypwu1** [comment]
@jaaufauvre  Golang is getting as popular as other main-stream programming language, Is there any plan for mastercard to build standard api client in go? if so, I would like to contribute.

**Comment by ech0s7r** [comment]
> we were working on [push-provisioning](https://developer.mastercard.com/page/push-provisioning) which uses mastercard api indirectly. And I used another [mastercard-api-client-tutorial](https://github.com/Mastercard/mastercard-api-client-tutorial) as reference.

Hi @ypwu1,
Some of the Mastercard services require the fingerprint computed from the *public key*, some other from the *certificate*. You can setup/generate the fingerprint within the library by setting properly the [service configuration](https://github.com/Mastercard/client-encryption-java/wiki/Service-Configurations-in-Java). In this [page](https://github.com/Mastercard/client-encryption-java/wiki/Service-Configurations-in-Java) we maintain a set of predefined service configurations for the MC services that requires encryption/decryption. 
We will review the service documentation you are integrating with, and check where the naming inconsistency could be. Thank you for reporting it.

> Golang is getting as popular as other main-stream programming language, Is there any plan for mastercard to build standard api client in go? if so, I would like to contribute.

Is the Go library hosted on GitHub?

**Comment by jaaufauvre** [comment]
Hi @ypwu1, can we close this one?
