### ISSUE TITLE
[REQ] Patching vulnerable dependencies

### ISSUE THREAD

**Issue by pf-BenF** [Mastercard/client-encryption-java#73]
### Is your feature request related to a problem? Please describe.
I've discovered a few vulnerable dependecies in test scope:

- org.codehaus.jettison:jettison 1.4.1
- net.minidev:json-smart 2.48
- com.fasterxml.jackson.core:jackson-databind 2.13.2.2

### Describe the solution you'd like

Upgrade mentioned dependencies to latest version

### Describe alternatives you've considered

Consider replacing vulnerable artifacts with alternatives.

**Comment by danny-gallagher** [comment]
Hi @pf-BenF,
Thanks for creating this issue! We've released version 1.7.9 of the client encryption library that addresses the following points:
- Bump jettison from 1.4.1 to 1.5.4
- Bump jackson-databind from 2.13.2.2 to 2.13.4.2 
- Bump json from 20200518 to 20230227
You should be able to see the new version on maven in the next couple of hours.
