### ISSUE TITLE
[BUG] Service Configurations for Client Encryption Java MDES Token Connect - missing Push Multiple Accounts configuration

### ISSUE THREAD

**Issue by Mikolaj-Walkowiak** [Mastercard/client-encryption-java#78]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
In the "Service Configurations for Client Encryption Java", the section "MDES Token Connect" misses the Encryption Path for the new Push Multiple Accounts payload. Using the default config results in an INVALID_JSON error.

**To Reproduce**
Use the provided FieldLevelEncryptionConfigBuilder for the MDES Token Connect.

**Expected behavior**
The payload is correctly encrypted.

**Suggest a fix/enhancement**
Add 
`  
 .withEncryptionPath("$.pushFundingAccounts.encryptedPayload.encryptedData", "$.pushFundingAccounts.encryptedPayload")
`
to the provided config, optionally mark 
`
.withEncryptionPath("$.pushFundingAccount.encryptedPayload.encryptedData", "$.pushFundingAccount.encryptedPayload")
`
as obsolete (or remove it altogether).

**Comment by ShimonaR-MC** [comment]
Closing with documentation update.
