### ISSUE TITLE
"Sonar Check" CI build step fails

### ISSUE THREAD

**Issue by olivier97** [Mastercard/client-encryption-java#83]
**Description**
The `Sonar Check` CI build step fails because the Java version used is no longer supported. I'd suggest bumping it to 17 or newer, as stated in the error message below (taken from the [latest workflow run](https://github.com/Mastercard/client-encryption-java/actions/runs/7583385415/job/20654906286)):
```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar (default-cli) on project client-encryption: 
Error:  
Error:  The version of Java (11.0.22) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
```

**To reproduce**
Push a commit (branch doesn't matter), or check the last few commits.

**Expected behavior**
The [SonarQube scanner plugin for maven](https://mvnrepository.com/artifact/org.sonarsource.scanner.maven/sonar-maven-plugin) can be executed successfully, allowing the "Sonar Check" build step to succeed.

**Suggest a fix/enhancement**
Bumping the [Java version used for executing the plugin](https://github.com/Mastercard/client-encryption-java/blob/59702f2/.github/workflows/sonar-scan.yml#L28) to `17` should fix the issue.

**Comment by ShimonaR-MC** [comment]
This is fixed by https://github.com/Mastercard/client-encryption-java/pull/81
